name: 'Python CI/CD'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r src/lambda/requirements.txt
        pip install -r src/glue/requirements.txt

    - name: Run tests
      run: |
        pytest

    - name: Package Lambda
      run: |
        cd src/lambda
        ./package_lambda.sh

    - name: Deploy to AWS
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'
      run: |
        aws lambda update-function-code --function-name university-survey-process --zip-file fileb://src/lambda/process_survey.zip
        aws s3 cp src/glue/etl_job.py s3://university-survey-glue-scripts/etl_job.py